"""Hybrid symbolic regression over complete EML trees."""

from .branch import BranchDiagnostics, principal_log_branch_diagnostics
from .compiler import CompilerConfig, CompileResult, UnsupportedExpression, compile_and_validate, compile_sympy_expression
from .expression import CenteredEml, Const, Eml, Expr, Geml, SympyCandidate, Var, ceml_expr, ceml_s_expr, exp_expr, geml_expr, ipi_eml_expr, log_expr, zeml_s_expr
from .geml_theory import build_ipi_restricted_theory, ipi_eml_value, write_ipi_restricted_theory
from .master_tree import EmbeddingConfig, SoftEMLTree, embed_expr_into_tree
from .semantics import (
    EmlOperator,
    ceml_operator,
    ceml_s_operator,
    centered_eml_numpy,
    centered_eml_torch,
    eml_numpy,
    eml_operator_from_spec,
    eml_torch,
    geml_numpy,
    geml_operator,
    geml_torch,
    ipi_eml_operator,
    raw_eml_operator,
    zeml_s_operator,
)
from .verify import VerificationReport, verify_candidate
from .witnesses import (
    CENTERED_FAMILY_SAME_FAMILY_WITNESS_MISSING,
    ScaffoldPlan,
    ScaffoldWitness,
    known_scaffold_kinds,
    list_scaffold_witnesses,
    resolve_scaffold_plan,
    scaffold_witness_for,
)

__all__ = [
    "CENTERED_FAMILY_SAME_FAMILY_WITNESS_MISSING",
    "BranchDiagnostics",
    "Const",
    "CenteredEml",
    "CompilerConfig",
    "CompileResult",
    "Eml",
    "EmlOperator",
    "EmbeddingConfig",
    "Expr",
    "Geml",
    "ScaffoldPlan",
    "ScaffoldWitness",
    "SoftEMLTree",
    "SympyCandidate",
    "UnsupportedExpression",
    "Var",
    "VerificationReport",
    "build_ipi_restricted_theory",
    "ceml_expr",
    "ceml_operator",
    "ceml_s_expr",
    "ceml_s_operator",
    "centered_eml_numpy",
    "centered_eml_torch",
    "compile_and_validate",
    "compile_sympy_expression",
    "eml_numpy",
    "eml_operator_from_spec",
    "eml_torch",
    "embed_expr_into_tree",
    "exp_expr",
    "geml_expr",
    "geml_numpy",
    "geml_operator",
    "geml_torch",
    "ipi_eml_expr",
    "ipi_eml_operator",
    "ipi_eml_value",
    "known_scaffold_kinds",
    "list_scaffold_witnesses",
    "log_expr",
    "principal_log_branch_diagnostics",
    "raw_eml_operator",
    "resolve_scaffold_plan",
    "scaffold_witness_for",
    "verify_candidate",
    "write_ipi_restricted_theory",
    "zeml_s_expr",
    "zeml_s_operator",
]
